
export const yayasanData = [
  {
    id: 1,
    logo: "🏛️",
    nama: "Yayasan Al-Azhar",
    npyp: "YY-00112",
    ketua: "Drs. H. Ahmad Fauzi, M.Pd",
    email: "info@yayasanalazhar.or.id",
    telepon: "(021) 7654321",
    website: "www.yayasanalazhar.or.id",
    alamat: "Jl. Kelapa Gading No. 10, Jakarta Utara",
    provinsi: "DKI Jakarta",
    kota: "Jakarta Utara",
    kecamatan: "Kelapa Gading",
    kelurahan: "Kelapa Gading Barat",
    kodePos: "14240",
    status: "Aktif",
    bergabung: "2023-01-10",
    jumlahSekolah: 3,
    totalGuru: 110,
    totalSiswa: 1680,
    totalAdmin: 6,
    sekolah: [
      "SMA Al-Azhar Kelapa Gading",
      "SMP Al-Azhar Kelapa Gading",
      "SD Al-Azhar Kelapa Gading",
    ],
  },

  {
    id: 2,
    logo: "🏛️",
    nama: "Yayasan BPK Penabur",
    npyp: "YY-00087",
    ketua: "Dra. Lidya Santoso",
    email: "sekretariat@bpkpenabur.or.id",
    telepon: "(021) 9876543",
    website: "www.bpkpenabur.or.id",
    alamat: "Jl. Kebon Jeruk No. 5, Jakarta Barat",
    provinsi: "DKI Jakarta",
    kota: "Jakarta Barat",
    kecamatan: "Kebon Jeruk",
    kelurahan: "Kebon Jeruk",
    kodePos: "11530",
    status: "Nonaktif",
    bergabung: "2022-08-10",
    jumlahSekolah: 2,
    totalGuru: 54,
    totalSiswa: 720,
    totalAdmin: 3,
    sekolah: [
      "SMP BPK Penabur",
      "SD BPK Penabur",
    ],
  },

  {
    id: 3,
    logo: "🏛️",
    nama: "Yayasan Pengembangan Pendidikan",
    npyp: "YY-00203",
    ketua: "Ir. Bambang Sutrisno",
    email: "kontak@yayasanppn.or.id",
    telepon: "(021) 5555555",
    website: "www.yayasanppn.or.id",
    alamat: "Jl. Bintaro Raya No. 20, Tangerang Selatan",
    provinsi: "Banten",
    kota: "Tangerang Selatan",
    kecamatan: "Bintaro",
    kelurahan: "Bintaro",
    kodePos: "15224",
    status: "Aktif",
    bergabung: "2024-06-01",
    jumlahSekolah: 1,
    totalGuru: 30,
    totalSiswa: 450,
    totalAdmin: 2,
    sekolah: [
      "SMA Taruna Nusantara",
    ],
  },

  {
    id: 4,
    logo: "🏛️",
    nama: "Yayasan Bina Insani",
    npyp: "YY-00155",
    ketua: "H. Slamet Riyadi, S.E.",
    email: "admin@binainsani.or.id",
    telepon: "(021) 3333333",
    website: "www.binainsani.or.id",
    alamat: "Jl. BSD Raya No. 8, Tangerang",
    provinsi: "Banten",
    kota: "Tangerang",
    kecamatan: "BSD",
    kelurahan: "BSD",
    kodePos: "15310",
    status: "Aktif",
    bergabung: "2024-04-05",
    jumlahSekolah: 1,
    totalGuru: 52,
    totalSiswa: 850,
    totalAdmin: 4,
    sekolah: [
      "SMK Bina Insani",
    ],
  },

  {
    id: 5,
    logo: "🏛️",
    nama: "Yayasan Al-Falah",
    npyp: "YY-00241",
    ketua: "Ust. Muhammad Iqbal, Lc",
    email: "sekretariat@alfalah.or.id",
    telepon: "(021) 2222222",
    website: "www.alfalah.or.id",
    alamat: "Jl. Depok Raya No. 12, Depok",
    provinsi: "Jawa Barat",
    kota: "Depok",
    kecamatan: "Depok",
    kelurahan: "Depok",
    kodePos: "16411",
    status: "Trial",
    bergabung: "2024-07-01",
    jumlahSekolah: 1,
    totalGuru: 25,
    totalSiswa: 340,
    totalAdmin: 2,
    sekolah: [
      "SMP Islam Terpadu Al-Falah",
    ],
  },
];


export const sekolahData = [
  {
    id: 1,
    nama: "SMA Al-Azhar Kelapa Gading",
    npsn: "20101620",
    jenjang: "SMA",
    status: "Aktif",
    yayasan: "Yayasan Al-Azhar",
    yayasanId: 1,
    kepalaSekolah: "Drs. Ahmad Fauzi, M.Pd",
    email: "info@smaalazhar.sch.id",
    telepon: "(021) 7654321",
    alamat: "Jl. Kelapa Gading No. 10, Jakarta Utara",
    provinsi: "DKI Jakarta",
    kota: "Jakarta Utara",
    kecamatan: "Kelapa Gading",
    kelurahan: "Kelapa Gading Barat",
    kodePos: "14240",
    jumlahGuru: 45,
    jumlahSiswa: 720,
    jumlahKelas: 24,
  },

  {
    id: 2,
    nama: "SMP Al-Azhar Kelapa Gading",
    npsn: "20101621",
    jenjang: "SMP",
    status: "Aktif",
    yayasan: "Yayasan Al-Azhar",
    yayasanId: 1,
    kepalaSekolah: "H. Budi Santoso, M.Pd",
    email: "info@smpalazhar.sch.id",
    telepon: "(021) 7654322",
    alamat: "Jl. Kelapa Gading No. 11, Jakarta Utara",
    provinsi: "DKI Jakarta",
    kota: "Jakarta Utara",
    kecamatan: "Kelapa Gading",
    kelurahan: "Kelapa Gading Barat",
    kodePos: "14240",
    jumlahGuru: 38,
    jumlahSiswa: 540,
    jumlahKelas: 18,
  },

  {
    id: 3,
    nama: "SD Al-Azhar Kelapa Gading",
    npsn: "20101622",
    jenjang: "SD",
    status: "Aktif",
    yayasan: "Yayasan Al-Azhar",
    yayasanId: 1,
    kepalaSekolah: "Dra. Siti Aminah",
    email: "info@sdalazhar.sch.id",
    telepon: "(021) 7654323",
    alamat: "Jl. Kelapa Gading No. 12, Jakarta Utara",
    provinsi: "DKI Jakarta",
    kota: "Jakarta Utara",
    kecamatan: "Kelapa Gading",
    kelurahan: "Kelapa Gading Barat",
    kodePos: "14240",
    jumlahGuru: 32,
    jumlahSiswa: 420,
    jumlahKelas: 18,
  },

  {
    id: 4,
    nama: "SMP BPK Penabur",
    npsn: "20102001",
    jenjang: "SMP",
    status: "Aktif",
    yayasan: "Yayasan BPK Penabur",
    yayasanId: 2,
    kepalaSekolah: "Dra. Lidya Santoso",
    email: "info@smpbpkpenabur.sch.id",
    telepon: "(021) 9876543",
    alamat: "Jl. Kebon Jeruk No. 5, Jakarta Barat",
    provinsi: "DKI Jakarta",
    kota: "Jakarta Barat",
    kecamatan: "Kebon Jeruk",
    kelurahan: "Kebon Jeruk",
    kodePos: "11530",
    jumlahGuru: 30,
    jumlahSiswa: 380,
    jumlahKelas: 12,
  },

  {
    id: 5,
    nama: "SD BPK Penabur",
    npsn: "20102002",
    jenjang: "SD",
    status: "Aktif",
    yayasan: "Yayasan BPK Penabur",
    yayasanId: 2,
    kepalaSekolah: "Dra. Maria Wijaya",
    email: "info@sdbpkpenabur.sch.id",
    telepon: "(021) 9876544",
    alamat: "Jl. Kebon Jeruk No. 6, Jakarta Barat",
    provinsi: "DKI Jakarta",
    kota: "Jakarta Barat",
    kecamatan: "Kebon Jeruk",
    kelurahan: "Kebon Jeruk",
    kodePos: "11530",
    jumlahGuru: 24,
    jumlahSiswa: 340,
    jumlahKelas: 12,
  },

  {
    id: 6,
    nama: "SMA Taruna Nusantara",
    npsn: "20203001",
    jenjang: "SMA",
    status: "Aktif",
    yayasan: "Yayasan Pengembangan Pendidikan",
    yayasanId: 3,
    kepalaSekolah: "Ir. Bambang Sutrisno",
    email: "info@smataruna.sch.id",
    telepon: "(021) 5555555",
    alamat: "Jl. Bintaro Raya No. 20, Tangerang Selatan",
    provinsi: "Banten",
    kota: "Tangerang Selatan",
    kecamatan: "Bintaro",
    kelurahan: "Bintaro",
    kodePos: "15224",
    jumlahGuru: 30,
    jumlahSiswa: 450,
    jumlahKelas: 15,
  },

  {
    id: 7,
    nama: "SMK Bina Insani",
    npsn: "20204001",
    jenjang: "SMK",
    status: "Aktif",
    yayasan: "Yayasan Bina Insani",
    yayasanId: 4,
    kepalaSekolah: "H. Slamet Riyadi, S.E.",
    email: "info@smkbinainsani.sch.id",
    telepon: "(021) 3333333",
    alamat: "Jl. BSD Raya No. 8, Tangerang",
    provinsi: "Banten",
    kota: "Tangerang",
    kecamatan: "BSD",
    kelurahan: "BSD",
    kodePos: "15310",
    jumlahGuru: 52,
    jumlahSiswa: 850,
    jumlahKelas: 24,
  },

  {
    id: 8,
    nama: "SMP Islam Terpadu Al-Falah",
    npsn: "20205001",
    jenjang: "SMP",
    status: "Trial",
    yayasan: "Yayasan Al-Falah",
    yayasanId: 5,
    kepalaSekolah: "Ust. Muhammad Iqbal, Lc",
    email: "info@smpalfalah.sch.id",
    telepon: "(021) 2222222",
    alamat: "Jl. Depok Raya No. 12, Depok",
    provinsi: "Jawa Barat",
    kota: "Depok",
    kecamatan: "Depok",
    kelurahan: "Depok",
    kodePos: "16411",
    jumlahGuru: 25,
    jumlahSiswa: 340,
    jumlahKelas: 12,
  },
];


export const dummyLangganan = [
  {
    id: 1,
    kode: "SUB-0001",
    sekolah: "SMA Al-Azhar Kelapa Gading",
    yayasan: "Yayasan Al-Azhar",
    paket: "Professional",
    periode: "Tahunan",
    harga: 15000000,
    tanggalMulai: "2026-08-11",
    tanggalBerakhir: "2027-08-11",
    status: "Aktif",
    pembayaran: "Lunas",
  },
  {
    id: 2,
    kode: "SUB-0002",
    sekolah: "SMP BPK Penabur",
    yayasan: "Yayasan BPK Penabur",
    paket: "Basic",
    periode: "6 Bulan",
    harga: 7500000,
    tanggalMulai: "2026-07-01",
    tanggalBerakhir: "2027-01-01",
    status: "Aktif",
    pembayaran: "Lunas",
  },
  {
    id: 3,
    kode: "SUB-0003",
    sekolah: "SMK Bina Insani",
    yayasan: "Yayasan Bina Insani",
    paket: "Enterprise",
    periode: "Tahunan",
    harga: 25000000,
    tanggalMulai: "2026-06-15",
    tanggalBerakhir: "2027-06-15",
    status: "Akan Berakhir",
    pembayaran: "Lunas",
  },
  {
    id: 4,
    kode: "SUB-0004",
    sekolah: "SMP Islam Terpadu Al-Falah",
    yayasan: "Yayasan Al-Falah",
    paket: "Basic",
    periode: "Bulanan",
    harga: 1500000,
    tanggalMulai: "2026-08-01",
    tanggalBerakhir: "2026-09-01",
    status: "Trial",
    pembayaran: "Pending",
  },
];

export const dummyRoles = [
  {
    id: "role-001",
    nama: "Super Admin",
    namaTampilan: "Super Admin",
    deskripsi: "Akses penuh ke seluruh modul dan pengaturan sistem SmartSchool.",
    status: "aktif",
    izin: 8,
    pengguna: 3,
    ikon: "Shield",
  },
  {
    id: "role-002",
    nama: "Admin Sekolah",
    namaTampilan: "Admin Sekolah",
    deskripsi: "Mengelola data sekolah, guru, siswa, dan kelas pada satu sekolah.",
    status: "aktif",
    izin: 4,
    pengguna: 125,
    ikon: "ShieldCheck",
  },
  {
    id: "role-003",
    nama: "Guru",
    namaTampilan: "Guru",
    deskripsi: "Mengelola nilai, presensi, dan materi ajar untuk kelas yang diampu.",
    status: "aktif",
    izin: 2,
    pengguna: 842,
    ikon: "BookOpen",
  },
  {
    id: "role-004",
    nama: "Wali Kelas",
    namaTampilan: "Wali Kelas",
    deskripsi: "Memantau perkembangan siswa dan mengelola data satu kelas.",
    status: "aktif",
    izin: 1,
    pengguna: 210,
    ikon: "UserCheck",
  },
  {
    id: "role-005",
    nama: "Bendahara",
    namaTampilan: "Bendahara",
    deskripsi: "Mengelola pembayaran, tagihan, dan laporan keuangan sekolah.",
    status: "nonaktif",
    izin: 2,
    pengguna: 18,
    ikon: "DollarSign",
  },
];

export const dummyPermissions = [
  { id: "perm-001", modul: "Akademik", aksi: "view", nama: "Lihat Akademik" },
  { id: "perm-002", modul: "Akademik", aksi: "create", nama: "Tambah Akademik" },
  { id: "perm-003", modul: "Akademik", aksi: "edit", nama: "Edit Akademik" },
  { id: "perm-004", modul: "Akademik", aksi: "delete", nama: "Hapus Akademik" },
  { id: "perm-005", modul: "Presensi", aksi: "view", nama: "Lihat Presensi" },
  { id: "perm-006", modul: "Presensi", aksi: "create", nama: "Tambah Presensi" },
  { id: "perm-007", modul: "Presensi", aksi: "edit", nama: "Edit Presensi" },
  { id: "perm-008", modul: "Presensi", aksi: "delete", nama: "Hapus Presensi" },
  { id: "perm-009", modul: "Keuangan", aksi: "view", nama: "Lihat Keuangan" },
  { id: "perm-010", modul: "Keuangan", aksi: "create", nama: "Tambah Keuangan" },
  { id: "perm-011", modul: "Keuangan", aksi: "edit", nama: "Edit Keuangan" },
  { id: "perm-012", modul: "Keuangan", aksi: "delete", nama: "Hapus Keuangan" },
  { id: "perm-013", modul: "Perpustakaan", aksi: "view", nama: "Lihat Perpustakaan" },
  { id: "perm-014", modul: "Perpustakaan", aksi: "create", nama: "Tambah Perpustakaan" },
  { id: "perm-015", modul: "Perpustakaan", aksi: "edit", nama: "Edit Perpustakaan" },
  { id: "perm-016", modul: "Perpustakaan", aksi: "delete", nama: "Hapus Perpustakaan" },
  { id: "perm-017", modul: "Kepegawaian", aksi: "view", nama: "Lihat Kepegawaian" },
  { id: "perm-018", modul: "Kepegawaian", aksi: "create", nama: "Tambah Kepegawaian" },
  { id: "perm-019", modul: "Kepegawaian", aksi: "edit", nama: "Edit Kepegawaian" },
  { id: "perm-020", modul: "Kepegawaian", aksi: "delete", nama: "Hapus Kepegawaian" },
  { id: "perm-021", modul: "Komunikasi", aksi: "view", nama: "Lihat Komunikasi" },
  { id: "perm-022", modul: "Komunikasi", aksi: "create", nama: "Tambah Komunikasi" },
  { id: "perm-023", modul: "Komunikasi", aksi: "edit", nama: "Edit Komunikasi" },
  { id: "perm-024", modul: "Komunikasi", aksi: "delete", nama: "Hapus Komunikasi" },
];